export const CATALOGO_SEED=[
  {categoria:"Láser Mujer - Zona Íntima",items:[
    {nombre:"Bikini Básico Mujer (8 ses)",precio:2250,precioPromo:2000,msi:[3]},
    {nombre:"Sexy Bikini Mujer (8 ses)",precio:2500,precioPromo:2250,msi:[3]},
    {nombre:"French Bikini Mujer (8 ses)",precio:3500,precioPromo:3000,msi:[3]},
    {nombre:"Bikini Brazilian Mujer (8 ses)",precio:4000,precioPromo:3500,msi:[3]},
    {nombre:"Crack Mujer (8 ses)",precio:1800,precioPromo:1625,msi:[]},
  ]},
  {categoria:"Láser Mujer - Cuerpo Inferior",items:[
    {nombre:"Coxis Mujer (8 ses)",precio:1800,precioPromo:1500,msi:[]},
    {nombre:"Glúteos Mujer (8 ses)",precio:2500,precioPromo:2250,msi:[3]},
    {nombre:"Medias Piernas Mujer (8 ses)",precio:3500,precioPromo:3000,msi:[3]},
    {nombre:"Piernas Completas Mujer (8 ses)",precio:5000,precioPromo:4500,msi:[3]},
    {nombre:"Pies Mujer (8 ses)",precio:1800,precioPromo:1500,msi:[]},
  ]},
  {categoria:"Láser Mujer - Cuerpo Superior",items:[
    {nombre:"Brazos Completos Mujer (8 ses)",precio:4000,precioPromo:3750,msi:[3]},
    {nombre:"Medios Brazos Mujer (8 ses)",precio:2800,precioPromo:2500,msi:[3]},
    {nombre:"Axilas Mujer (8 ses)",precio:1800,precioPromo:1500,msi:[]},
    {nombre:"Manos Mujer (8 ses)",precio:1500,precioPromo:1250,msi:[]},
    {nombre:"Espalda Completa Mujer (8 ses)",precio:4800,precioPromo:4500,msi:[3]},
    {nombre:"Media Espalda Mujer (8 ses)",precio:2500,precioPromo:2250,msi:[3]},
    {nombre:"Hombros Mujer (8 ses)",precio:2000,precioPromo:1750,msi:[]},
    {nombre:"Abdomen Mujer (8 ses)",precio:2250,precioPromo:2000,msi:[3]},
    {nombre:"Línea de Abdomen Mujer (8 ses)",precio:1500,precioPromo:1250,msi:[]},
    {nombre:"Pecho Mujer (8 ses)",precio:2250,precioPromo:2500,msi:[3]},
    {nombre:"Pezones Mujer (8 ses)",precio:1500,precioPromo:1250,msi:[]},
  ]},
  {categoria:"Láser Mujer - Rostro",items:[
    {nombre:"Rostro Completo Mujer (8 ses)",precio:2750,precioPromo:2500,msi:[3]},
    {nombre:"Medio Rostro Mujer (8 ses)",precio:2250,precioPromo:2000,msi:[3]},
    {nombre:"Cuello Mujer (8 ses)",precio:1800,precioPromo:1500,msi:[]},
    {nombre:"Nuca Mujer (8 ses)",precio:1800,precioPromo:1500,msi:[]},
    {nombre:"Bigote Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
    {nombre:"Entreceja Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
    {nombre:"Frente Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
    {nombre:"Mejillas Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
    {nombre:"Mentón Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
    {nombre:"Patillas Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
    {nombre:"Nariz Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
    {nombre:"Orejas Mujer (8 ses)",precio:1250,precioPromo:1000,msi:[]},
  ]},
  {categoria:"Combos Láser Mujer",items:[
    {nombre:"Combo Abdomen Mujer (8 ses)",precio:4500,msi:[3]},
    {nombre:"Combo Axilas Mujer (8 ses)",precio:5000,precioPromo:5500,msi:[3]},
    {nombre:"Combo Glúteos Mujer (8 ses)",precio:5500,msi:[3]},
    {nombre:"Combo Bikini Mujer (8 ses)",precio:5000,precioPromo:4500,msi:[3]},
    {nombre:"Combo Piernas Mujer (8 ses)",precio:6500,precioPromo:7000,msi:[3,6]},
    {nombre:"Combo Brazos Mujer (8 ses)",precio:5500,precioPromo:6000,msi:[3]},
    {nombre:"Combo Playa Básico Mujer (8 ses)",precio:6750,precioPromo:7000,msi:[3,6]},
    {nombre:"Combo Playa Sexy Mujer (8 ses)",precio:6750,precioPromo:7000,msi:[3,6]},
    {nombre:"Combo Playa French Mujer (8 ses)",precio:6750,precioPromo:7000,msi:[3,6]},
    {nombre:"Combo Playa Brazilian Mujer (8 ses)",precio:6750,precioPromo:7000,msi:[3,6]},
    {nombre:"Combo Sexy Básico Mujer (8 ses)",precio:7750,precioPromo:8000,msi:[3,6]},
    {nombre:"Combo Sexy Sexy Mujer (8 ses)",precio:7750,precioPromo:8000,msi:[3,6]},
    {nombre:"Combo Sexy French Mujer (8 ses)",precio:7750,precioPromo:8000,msi:[3,6]},
    {nombre:"Combo Sexy Brazilian Mujer (8 ses)",precio:7750,precioPromo:8000,msi:[3,6]},
    {nombre:"Combo Rostro Mujer (8 ses)",precio:8500,precioPromo:9000,msi:[3,6]},
    {nombre:"Cuerpo Completo Mujer (8 ses)",precio:10500,precioPromo:9500,msi:[3,6,9]},
  ]},
  {categoria:"Láser Hombre - Zona Íntima",items:[
    {nombre:"Classic Boy Bikini (8 ses)",precio:2750,msi:[3]},
    {nombre:"Classic Boy Bikini Plus (8 ses)",precio:3750,msi:[3]},
    {nombre:"French Boy Bikini (8 ses)",precio:4250,msi:[3]},
    {nombre:"Boy Bikini Brazilian (8 ses)",precio:6000,msi:[3,6]},
    {nombre:"Crackman (8 ses)",precio:1875,precioPromo:1300,msi:[]},
  ]},
  {categoria:"Láser Hombre - Cuerpo Inferior",items:[
    {nombre:"Coxis Hombre (8 ses)",precio:1800,msi:[]},
    {nombre:"Glúteos con Crack Hombre (8 ses)",precio:2500,precioPromo:1600,msi:[3]},
    {nombre:"Glúteos sin Crack Hombre (8 ses)",precio:2500,precioPromo:1600,msi:[3]},
    {nombre:"Medias Piernas Abajo Hombre (8 ses)",precio:3500,precioPromo:2400,msi:[3]},
    {nombre:"Medias Piernas Arriba Hombre (8 ses)",precio:3500,precioPromo:2400,msi:[3]},
    {nombre:"Piernas Completas Hombre (8 ses)",precio:5000,msi:[3]},
    {nombre:"Pies Hombre (8 ses)",precio:1800,msi:[]},
  ]},
  {categoria:"Láser Hombre - Cuerpo Superior",items:[
    {nombre:"Brazos Completos Hombre (8 ses)",precio:4000,precioPromo:3000,msi:[3]},
    {nombre:"Medios Brazos Hombre (8 ses)",precio:2800,precioPromo:2000,msi:[3]},
    {nombre:"Axilas Hombre (8 ses)",precio:1800,precioPromo:1200,msi:[]},
    {nombre:"Manos Hombre (8 ses)",precio:1800,msi:[]},
    {nombre:"Espalda Completa Hombre (8 ses)",precio:5250,precioPromo:3600,msi:[3]},
    {nombre:"Media Espalda Abajo Hombre (8 ses)",precio:2750,msi:[3]},
    {nombre:"Media Espalda Arriba Hombre (8 ses)",precio:2750,msi:[3]},
    {nombre:"Hombros Hombre (8 ses)",precio:2000,msi:[]},
    {nombre:"Abdomen Hombre (8 ses)",precio:2250,precioPromo:1600,msi:[3]},
    {nombre:"Línea de Abdomen Hombre (8 ses)",precio:1800,precioPromo:1000,msi:[]},
    {nombre:"Pecho Hombre (8 ses)",precio:3550,msi:[3]},
    {nombre:"Pezones Hombre (8 ses)",precio:1800,msi:[]},
  ]},
  {categoria:"Láser Hombre - Rostro",items:[
    {nombre:"Rostro Completo Hombre (8 ses)",precio:3250,precioPromo:2000,msi:[3]},
    {nombre:"Barba Hombre (8 ses)",precio:2750,msi:[3]},
    {nombre:"Cuello Hombre (8 ses)",precio:2750,msi:[]},
    {nombre:"Nuca Hombre (8 ses)",precio:2750,msi:[]},
    {nombre:"Bigote Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Contorno de Ojos Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Entreceja Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Frente Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Mejillas Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Mentón Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Patillas Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Nariz Hombre (8 ses)",precio:1500,msi:[]},
    {nombre:"Orejas Hombre (8 ses)",precio:1500,msi:[]},
  ]},
  {categoria:"Combos Láser Hombre",items:[
    {nombre:"Combo Pecho Hombre (8 ses)",precio:5250,msi:[3]},
    {nombre:"Combo Men (8 ses)",precio:8250,msi:[3,6]},
    {nombre:"Combo Espalda Hombre (8 ses)",precio:7250,msi:[3,6]},
    {nombre:"Combo Glúteos Hombre (8 ses)",precio:7750,msi:[3,6]},
    {nombre:"Combo Pride (8 ses)",precio:10250,msi:[3,6]},
    {nombre:"Cuerpo Completo Hombre (8 ses)",precio:11000,precioPromo:8500,msi:[3,6,9]},
  ]},
  {categoria:"Faciales",items:[
    {nombre:"Skin Renew (1 ses)",precio:649,msi:[]},
    {nombre:"Skin Renew (3 ses)",precio:1799,msi:[]},
    {nombre:"Skin Renew (5 ses)",precio:2945,msi:[]},
    {nombre:"Skin Renew (10 ses)",precio:5000,msi:[3]},
    {nombre:"Skin Repair (1 ses)",precio:949,msi:[]},
    {nombre:"Skin Repair (3 ses)",precio:2547,msi:[]},
    {nombre:"Skin Repair (5 ses)",precio:3745,msi:[]},
    {nombre:"Skin Repair (10 ses)",precio:6490,precioPromo:5100,msi:[3]},
    {nombre:"Skin Reset (1 ses)",precio:949,msi:[]},
    {nombre:"Skin Reset (3 ses)",precio:2547,msi:[]},
    {nombre:"Skin Reset (5 ses)",precio:3745,msi:[]},
    {nombre:"Skin Reset (10 ses)",precio:6490,msi:[3]},
  ]},
  {categoria:"Cire Lift (HIFU 4D)",items:[
    {nombre:"Cire Lift 1 sesión",precio:3250,precioPromo:2500,msi:[3]},
    {nombre:"Cire Lift 2 sesiones",precio:5500,msi:[3]},
  ]},
  {categoria:"Cire Body (Moldeo Corporal)",items:[
    {nombre:"Cire Body 1 sesión",precio:749,precioPromo:625,msi:[]},
    {nombre:"Cire Body 6 sesiones",precio:3500,precioPromo:3399,msi:[3]},
    {nombre:"Cire Body 12 sesiones",precio:6290,precioPromo:5949,msi:[3]},
  ]},
  {categoria:"Moldeo Cire-Na",items:[
    {nombre:"Moldeo Cire-Na 1 ses",precio:749,precioPromo:625,msi:[]},
    {nombre:"Moldeo Cire-Na 6 ses",precio:3500,precioPromo:3399,msi:[3]},
    {nombre:"Moldeo Cire-Na 12 ses",precio:6290,precioPromo:5949,msi:[3]},
  ]},
  {categoria:"Cire Sculpt Anticelulítico",items:[
    {nombre:"Cire Sculpt Anti 1 ses",precio:749,precioPromo:625,msi:[]},
    {nombre:"Cire Sculpt Anti 6 ses",precio:3500,precioPromo:3399,msi:[3]},
    {nombre:"Cire Sculpt Anti 12 ses",precio:6290,precioPromo:5949,msi:[3]},
  ]},
  {categoria:"Cire Sculpt Post Operatorio",items:[
    {nombre:"Post Op 1 ses",precio:899,precioPromo:899,msi:[]},
    {nombre:"Post Op 6 ses",precio:4000,msi:[3]},
    {nombre:"Post Op 12 ses",precio:7490,msi:[3]},
  ]},
  {categoria:"Cera",items:[
    {nombre:"Cera Bikini Básico",precio:390,msi:[]},
    {nombre:"Cera Sexy Bikini",precio:460,msi:[]},
    {nombre:"Cera French Bikini",precio:520,msi:[]},
    {nombre:"Cera Bikini Brazilian",precio:590,msi:[]},
    {nombre:"Cera Crack",precio:200,msi:[]},
    {nombre:"Cera Coxis",precio:130,msi:[]},
    {nombre:"Cera Glúteos con Crack",precio:320,msi:[]},
    {nombre:"Cera Glúteos sin Crack",precio:240,msi:[]},
    {nombre:"Cera Medias Piernas Arriba",precio:410,msi:[]},
    {nombre:"Cera Medias Piernas Abajo",precio:430,msi:[]},
    {nombre:"Cera Piernas Completas",precio:690,msi:[]},
    {nombre:"Cera Pies",precio:130,msi:[]},
    {nombre:"Cera Abdomen",precio:240,msi:[]},
    {nombre:"Cera Combo Abdomen + Pecho",precio:550,msi:[]},
    {nombre:"Cera Axilas",precio:150,msi:[]},
    {nombre:"Cera Brazos Completos",precio:410,msi:[]},
    {nombre:"Cera Espalda Completa",precio:550,msi:[]},
    {nombre:"Cera Hombros",precio:200,msi:[]},
    {nombre:"Cera Línea de Abdomen",precio:130,msi:[]},
    {nombre:"Cera Manos",precio:130,msi:[]},
    {nombre:"Cera Media Espalda Superior",precio:280,msi:[]},
    {nombre:"Cera Media Espalda Inferior",precio:300,msi:[]},
    {nombre:"Cera Medios Brazos",precio:340,msi:[]},
    {nombre:"Cera Pecho",precio:280,msi:[]},
    {nombre:"Cera Pezones",precio:130,msi:[]},
    {nombre:"Cera Barba",precio:330,msi:[]},
    {nombre:"Cera Bigote",precio:110,msi:[]},
    {nombre:"Cera Diseño de Cejas",precio:300,msi:[]},
    {nombre:"Cera Entreceja",precio:70,msi:[]},
    {nombre:"Cera Frente",precio:130,msi:[]},
    {nombre:"Cera Mantenimiento de Cejas",precio:260,msi:[]},
    {nombre:"Cera Medio Rostro",precio:460,msi:[]},
    {nombre:"Cera Mejillas",precio:130,msi:[]},
    {nombre:"Cera Mentón",precio:130,msi:[]},
    {nombre:"Cera Patillas",precio:130,msi:[]},
    {nombre:"Cera Rostro Completo con Diseño de Ceja",precio:780,msi:[]},
    {nombre:"Cera Rostro Completo con Mantenimiento de Ceja",precio:720,msi:[]},
    {nombre:"Cera Rostro Completo sin Cejas",precio:590,msi:[]},
    {nombre:"Cera Nariz",precio:100,msi:[]},
    {nombre:"Cera Nuca",precio:130,msi:[]},
    {nombre:"Cera Orejas",precio:130,msi:[]},
    {nombre:"Cera Combo Sexy Básico",precio:1170,msi:[]},
    {nombre:"Cera Combo Sexy Sexy Bikini",precio:1300,msi:[]},
    {nombre:"Cera Combo Sexy French",precio:1370,msi:[]},
    {nombre:"Cera Combo Sexy Brazilian",precio:1410,msi:[]},
    {nombre:"Cera Combo Playa Básico",precio:980,msi:[]},
    {nombre:"Cera Combo Playa Sexy Bikini",precio:1040,msi:[]},
    {nombre:"Cera Combo Playa French",precio:1110,msi:[]},
    {nombre:"Cera Combo Playa Brazilian",precio:1170,msi:[]},
    {nombre:"Cera Combo Piernas French",precio:1170,msi:[]},
    {nombre:"Cera Combo Piernas Brazilian",precio:1240,msi:[]},
    {nombre:"Cera Cuerpo Completo con Rostro",precio:3250,msi:[]},
    {nombre:"Cera Cuerpo Completo sin Rostro",precio:2930,msi:[]},
  ]},
  {categoria:"Aparatología",items:[
    {nombre:"Aparatología 1 zona",precio:649,msi:[]},
  ]},
  {categoria:"Productos",items:[
    {nombre:"Inhibidor de vello Beautive",precio:500,msi:[]},
    {nombre:"Exfoliante corporal Beautive",precio:500,msi:[]},
    {nombre:"Moisten Ácido Hialurónico",precio:1200,msi:[]},
    {nombre:"Moisten PDRN",precio:1200,msi:[]},
    {nombre:"Depilsense Inhibidor de Vello Aspid Pro",precio:959,msi:[]},
    {nombre:"Talco Líquido Despigmentante Aspid Pro",precio:819,msi:[]},
    {nombre:"Moisten Crema",precio:1400,msi:[]},
  ]},
  {categoria:"Paquetes Especiales",items:[
    {nombre:"Paquete de Bienestar (Masaje Relajante + Facial Skin Repair, 2h)",precio:1500,msi:[],sucursales:["Oriente","Polanco"]},
  ]},
];
